= Using =importxml for live updating sheets

=== Pull any web element into a Google Sheet.

Quite often I'll have a spreadsheet that requires a piece of data that is regularly updated on a website (and not accessible though an api). ImportXML allows me to pull _just about_ any element or array of elements onto a sheet to be operated on. Great for creating simple, low maintenence dashboards. To share a dashboard without sharing the sheet just publish a table and/or charts to a visible web page (be sure to add app scripts trigger to keep data fresh).

==== Search results:
XXXX Move Here

==== Single element:
XXXX Move Here
XML/JSON & XPATH

==== Commonly used queries
Concat vs direct +
Xml guide +
Comb through notes. +
Add links to xmlpath chrome extensions.

==== A basic web scraper
Even though I'm capable with more advanced tools to capture(scrape) web data I still use importxml and sheets 90% of the time since it is so easy and is captured in sheets which allows it to be manipulated immediatly. 